### ISSUE TITLE
The Mapbox token is publicly exposed

### ISSUE THREAD

**Issue by nerik** [batpad/videomap#14]
The Mapbox token used for the map is exposed. We need to move on from GH pages if we want to fix that.
Is the current token scoped to only videomap.earth? 

@batpad cc @wrynearson

**Comment by batpad** [comment]
> We need to move on from GH pages if we want to fix that.

How do you mean? AFAIK, the mapbox public token is always exposed on the client application? It's part of the request, so there's no real way to "hide" it in the client application.

We can probably do a couple of things:

 - Remove it from the github repository. I can ticket that out separately if that's something we want to do. Should be straightforward to add it as a Secret to the repo and just substitute it in before the github publish step. Will be a little bit of fiddling with GH Actions, but it should be fine to still use GH pages, we'd just need to add a build step that reads from the secret / environment before publishing. We could also use some existing build tool that would read from the environment and substitute secrets.
 - Scope the token referer to videomap.earth and localhost . @geohacker very sorry - I think I asked you to generate this token for me :( - can coordinate when we speak next - just make sure it's a fresh token, and add the referer scoping.

Thanks for ticketing @nerik - I see these as nice to do, but not critically urgent - let me know if I'm missing something..

**Comment by geohacker** [comment]
Ah bummer. Thanks for catching @nerik. I've disabled that token. It's a bit irritating because that was my default token so now I'll likely have to chase all the broken maps 😭

**Comment by geohacker** [comment]
But also this isn't really a big issue — by default the public token is always exposed. Anyway a good reminder for me to cycle them because I've not done that in a long time.

**Comment by nerik** [comment]
That was initially caught by @wrynearson (thank you!)

I'm like the opposite of a security expert, so defaulting on paranoid borderline dumb whenever I have a shred of doubt. The reasoning goes like this: public repos on Github are exposed via APIs, so one could theoretically scrape a ton of `MAPBOX_TOKEN` instances and, I don't know, do evil stuff (even though yes, eventually that token is perfectly visible in the browser). Maybe I'm a fool, but a sanitary measure at least is to use Mapbox token scoping feature. 


![d](https://media.giphy.com/media/YQitE4YNQNahy/giphy-downsized.gif)

**Comment by batpad** [comment]
Closing this as fundamentally "not an issue" since every Mapbox map exposes the public token.

Let's just create a new token that we use only for this project to follow good hygiene, but @geohacker I don't think you need to worry beyond that.
